### ISSUE TITLE
Timeout on vagrant up

### ISSUE THREAD

**Issue by NEOAdvancedTechnology** [bbc/nmos-joint-ri#8]
I've tried a couple of times now, on AWS S3 instances of reasonable power (c5.xlarge) with both Ubuntu 16.04 and AWS Linux, and keep getting this:

```
==> regquery: Waiting for machine to boot. This may take a few minutes...
    regquery: SSH address: 127.0.0.1:2222
    regquery: SSH username: vagrant
    regquery: SSH auth method: private key
Timed out while waiting for the machine to boot. 
```

It never gets to starting the node...

```
$ vagrant global-status
Configuring proxy settings...
id       name     provider   state   directory                            
--------------------------------------------------------------------------
115e96d  regquery virtualbox running /home/ec2-user/nmos-joint-ri/vagrant 
```

Any way to check the logs to see what is happening?

(A super-cool idea would be to have an AWS S3 AMI of the joint-ri available)

**Comment by andrewbonney** [comment]
> I've tried a couple of times now, on AWS S3 instances of reasonable power (c5.xlarge) with both Ubuntu 16.04 and AWS Linux, and keep getting this

It should be possible to increase the timeout for specific cases by editing the following entries in the Vagrantfile. Could you try changing these and let us know if it helps? `regquery.vm.boot_timeout = 600` and `node.vm.boot_timeout = 600`.

> Any way to check the logs to see what is happening?

There's a bit about debug logging here: https://www.vagrantup.com/docs/other/debugging.html. This issue is before the point at which any software is installed, so it's just about bootstrapping the OS.

> (A super-cool idea would be to have an AWS S3 AMI of the joint-ri available)

Yes, we've also previously had pre-built VirtualBox OVA images available too with builds via Packer. Unfortunately I think it's unlikely we're going to have the time to work on this sort of thing any time soon.

**Comment by andrewjohnwatts** [comment]
Appreciate this was reported a while ago but I'm seeing the same issue where it is timing out at the point it tries to SSH into the machine.

I suspect that it's something to do with my setup rather than your code specifically but I've not been able to get this to run since ansible was introduced (I know that was a while ago). 

Any pointers would be appreciated though please. I've uploaded the debug output to gist here:
[https://gist.github.com/andrewjohnwatts/c08b8fc619867ec26bd354bf7e73ff17)](https://gist.github.com/andrewjohnwatts/c08b8fc619867ec26bd354bf7e73ff17)

(I'm running Ubuntu 16.04 LTS).

**Comment by JamesGibo** [comment]
To test if this is caused by a someithing on your system of the joint ri, please could you try testing running a simple vagrant file, for example:
```ruby
Vagrant.configure("2") do |config|
  # keep SSH connection alive
  config.ssh.keep_alive = true

  config.vm.define "testing" do |testing|
    testing.vm.box = "bento/ubuntu-18.04"
    testing.vm.hostname = "testing"
    testing.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.linked_clone = true
      vb.memory = 1024
      vb.customize ["modifyvm", :id, "--uartmode1", "disconnected" ]
      vb.customize ["storagectl", :id, "--name", "SATA Controller", "--hostiocache", "on" ]
    end
  end
end
```

And then try ssh into the virtual machine `vagrant ssh testing`

If this does not work, then is might be worth clearing any cached images in virtual box and vagrant

**Comment by andrewjohnwatts** [comment]
Sorry I should have thought to test this before commenting - it looks like I've got an issue with vagrant and nested VMs on my setup. Please disregard this.
